
import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Lightbulb, ArrowRight, TrendingUp, BookOpen, UserCheck } from 'lucide-react';

const recommendations = [
  {
    id: '1',
    type: 'reassignment',
    priority: 'High',
    title: 'Reassign Amit Shah to Training Program',
    description: 'Current mismatch detected. Worker lacks critical skills for Quality Control Analyst role.',
    impact: 'Reduce safety risk by 40%',
    action: 'Enroll in Advanced Testing certification',
    timeline: '2 weeks',
    icon: BookOpen,
    color: 'bg-orange-50 border-orange-200'
  },
  {
    id: '2',
    type: 'optimization',
    priority: 'Medium',
    title: 'Cross-train Priya Patel in Quality Assurance',
    description: 'High-performing supervisor could fill skill gap in QA department.',
    impact: 'Increase department flexibility by 25%',
    action: 'Add Quality Assurance training to schedule',
    timeline: '1 month',
    icon: TrendingUp,
    color: 'bg-blue-50 border-blue-200'
  },
  {
    id: '3',
    type: 'promotion',
    priority: 'Low',
    title: 'Promote Rajesh Kumar to Lead Operator',
    description: 'Exceptional performance and skill match. Ready for increased responsibilities.',
    impact: 'Improve team efficiency by 15%',
    action: 'Schedule leadership assessment',
    timeline: '1 week',
    icon: UserCheck,
    color: 'bg-green-50 border-green-200'
  }
];

export const RecommendationPanel = () => {
  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case 'High': return 'bg-red-100 text-red-800';
      case 'Medium': return 'bg-yellow-100 text-yellow-800';
      case 'Low': return 'bg-green-100 text-green-800';
      default: return 'bg-gray-100 text-gray-800';
    }
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center space-x-2">
          <Lightbulb className="h-5 w-5 text-yellow-500" />
          <span>AI-Powered Recommendations</span>
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        {recommendations.map((rec) => {
          const Icon = rec.icon;
          return (
            <div key={rec.id} className={`p-4 rounded-lg border-2 ${rec.color}`}>
              <div className="flex items-start justify-between mb-3">
                <div className="flex items-center space-x-3">
                  <div className="p-2 bg-white rounded-lg">
                    <Icon className="h-4 w-4" />
                  </div>
                  <div>
                    <h3 className="font-semibold">{rec.title}</h3>
                    <p className="text-sm text-gray-600 mt-1">{rec.description}</p>
                  </div>
                </div>
                <Badge className={getPriorityColor(rec.priority)}>
                  {rec.priority}
                </Badge>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-4 text-sm">
                <div>
                  <span className="text-gray-600">Expected Impact:</span>
                  <p className="font-medium text-green-700">{rec.impact}</p>
                </div>
                <div>
                  <span className="text-gray-600">Recommended Action:</span>
                  <p className="font-medium">{rec.action}</p>
                </div>
                <div>
                  <span className="text-gray-600">Timeline:</span>
                  <p className="font-medium">{rec.timeline}</p>
                </div>
              </div>

              <div className="flex items-center justify-between">
                <div className="flex items-center space-x-2 text-sm text-gray-600">
                  <span>Generated by AI • Based on performance data</span>
                </div>
                <div className="flex space-x-2">
                  <Button variant="outline" size="sm">
                    Dismiss
                  </Button>
                  <Button size="sm" className="flex items-center space-x-1">
                    <span>Implement</span>
                    <ArrowRight className="h-3 w-3" />
                  </Button>
                </div>
              </div>
            </div>
          );
        })}
        
        <div className="mt-6 p-4 bg-gradient-to-r from-blue-50 to-indigo-50 rounded-lg border border-blue-200">
          <div className="flex items-center justify-between">
            <div>
              <h3 className="font-semibold text-blue-900">Weekly Optimization Report</h3>
              <p className="text-sm text-blue-700 mt-1">
                Implementing these recommendations could improve overall productivity by 18%
              </p>
            </div>
            <Button variant="outline" className="border-blue-300 text-blue-700 hover:bg-blue-100">
              View Full Report
            </Button>
          </div>
        </div>
      </CardContent>
    </Card>
  );
};
